const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8",...CORS,...extra}});
const now=()=>new Date().toISOString();
export default {async fetch(request,env){
  const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{headers:CORS});
  try{
    if(!env.DB)throw new Error('Missing D1 binding: DB');if(!env.ASSETS)throw new Error('Missing R2 binding: ASSETS');
    if(url.pathname==='/api/health')return json({ok:true,service:'fluency-engine-public',version:'0.9.6.4',storage:'r2',pwa:true,course_packages:'zip',image_catalog:'shared'});
    if(url.pathname==='/api/catalog'&&request.method==='GET')return catalog(env);
    if(url.pathname.match(/^\/api\/course\/[^/]+\/versions$/)&&request.method==='GET')return versions(url,env);
    if(url.pathname.match(/^\/api\/course\/[^/]+\/package\/[^/]+$/)&&request.method==='GET')return coursePackage(url,env);
    if(url.pathname.match(/^\/api\/course\/[^/]+\/version\/[^/]+$/)&&request.method==='GET')return courseVersion(url,env);
    if(url.pathname.startsWith('/api/course/')&&request.method==='GET')return course(url,env);
    if(url.pathname.startsWith('/media/')&&request.method==='GET')return media(url,env);
    if(url.pathname==='/api/analytics/batch'&&request.method==='POST')return analytics(request,env);
    if(env.STATIC)return env.STATIC.fetch(request);
    return json({error:'Not found'},404);
  }catch(e){return json({error:e.message||String(e)},500)}
}};
async function catalog(env){const r=await env.DB.prepare(`SELECT c.course_id,c.title_en,c.title_kh,c.current_version_id,v.version_label,v.content_sha256,v.byte_size FROM courses c LEFT JOIN course_versions v ON v.version_id=c.current_version_id WHERE c.published=1 ORDER BY c.course_id`).all();return json({courses:r.results.map(x=>({...x,download_url:`/api/course/${encodeURIComponent(x.course_id)}`,package_url:`/api/course/${encodeURIComponent(x.course_id)}/package/${encodeURIComponent(x.version_label||'')}`}))},200,{'Cache-Control':'public, max-age=60'})}
async function course(url,env){const id=decodeURIComponent(url.pathname.slice('/api/course/'.length)),row=await env.DB.prepare(`SELECT v.r2_object_key,v.content_sha256 FROM courses c JOIN course_versions v ON v.version_id=c.current_version_id WHERE c.course_id=? AND c.published=1`).bind(id).first();if(!row)return json({error:'Course not found'},404);const obj=await env.ASSETS.get(row.r2_object_key);if(!obj)return json({error:'Course object missing from R2'},500);const h=new Headers(CORS);obj.writeHttpMetadata(h);h.set('Content-Type','application/json; charset=utf-8');h.set('Cache-Control','public,max-age=300,s-maxage=3600');if(row.content_sha256)h.set('ETag',`"${row.content_sha256}"`);return new Response(obj.body,{headers:h})}
async function media(url,env){const key=decodeURIComponent(url.pathname.slice('/media/'.length)).replace(/^\/+/, '');if(!key||key.includes('..'))return json({error:'Invalid media path'},400);const obj=await env.ASSETS.get(key);if(!obj)return json({error:'Media not found'},404);const h=new Headers(CORS);obj.writeHttpMetadata(h);h.set('Cache-Control','public,max-age=31536000,immutable');return new Response(obj.body,{headers:h})}
async function analytics(request,env){const body=await request.json(),events=Array.isArray(body.events)?body.events.slice(0,500):[];for(const e of events)await env.DB.prepare(`INSERT OR IGNORE INTO analytics_events(event_id,installation_id,event_type,course_id,lesson_id,card_index,payload_json,created_at,app_version) VALUES(?,?,?,?,?,?,?,?,?)`).bind(e.id,e.installation_id,e.type,e.course_id||'',e.lesson_id||'',Number.isInteger(e.card_index)?e.card_index:null,JSON.stringify(e),e.created_at||now(),e.app_version||'').run();return json({accepted:events.length})}

async function versions(url,env){const parts=url.pathname.split('/'),id=decodeURIComponent(parts[3]);const r=await env.DB.prepare(`SELECT version_id,version_label,content_sha256,byte_size,published_at FROM course_versions WHERE course_id=? AND status='published' ORDER BY published_at DESC`).bind(id).all();return json({course_id:id,versions:r.results})}
async function courseVersion(url,env){const parts=url.pathname.split('/'),id=decodeURIComponent(parts[3]),label=decodeURIComponent(parts[5]);const row=await env.DB.prepare(`SELECT r2_object_key,content_sha256 FROM course_versions WHERE course_id=? AND version_label=? AND status='published'`).bind(id,label).first();if(!row)return json({error:'Course version not found'},404);const obj=await env.ASSETS.get(row.r2_object_key);if(!obj)return json({error:'Course object missing from R2'},500);const h=new Headers(CORS);obj.writeHttpMetadata(h);h.set('Content-Type','application/json; charset=utf-8');h.set('Cache-Control','public,max-age=31536000,immutable');if(row.content_sha256)h.set('ETag',`"${row.content_sha256}"`);return new Response(obj.body,{headers:h})}

function collectAssetKeys(c){const s=new Set();const add=x=>{if(!x)return;const k=typeof x==='string'?x:(x.r2_key||x.path);if(k)s.add(String(k).replace(/^\/+/,''))};for(const x of c?.assets?.images||[])add(x);for(const l of c.lessons||[]){for(const sk of l.skills||[])add(sk.image);for(const a of l.activities||[]){add(a.model_audio);add(a.image);for(const t of a.turns||[])add(t.audio)}}return [...s]}
function crc32(bytes){let c=-1;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xEDB88320:0)}return (c^-1)>>>0}
function u16(a,n){a.push(n&255,(n>>>8)&255)}function u32(a,n){a.push(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255)}
function makeStoredZip(files){const enc=new TextEncoder(),out=[],central=[];let off=0;for(const f of files){const name=enc.encode(f.name),data=f.bytes,crc=crc32(data),local=[];u32(local,0x04034b50);u16(local,20);u16(local,0);u16(local,0);u16(local,0);u16(local,0);u32(local,crc);u32(local,data.length);u32(local,data.length);u16(local,name.length);u16(local,0);local.push(...name);out.push(...local,...data);const cen=[];u32(cen,0x02014b50);u16(cen,20);u16(cen,20);u16(cen,0);u16(cen,0);u16(cen,0);u16(cen,0);u32(cen,crc);u32(cen,data.length);u32(cen,data.length);u16(cen,name.length);u16(cen,0);u16(cen,0);u16(cen,0);u16(cen,0);u32(cen,0);u32(cen,off);cen.push(...name);central.push(...cen);off+=local.length+data.length}const cdOff=out.length;out.push(...central);const end=[];u32(end,0x06054b50);u16(end,0);u16(end,0);u16(end,files.length);u16(end,files.length);u32(end,central.length);u32(end,cdOff);u16(end,0);out.push(...end);return new Uint8Array(out)}
async function sha256Hex(bytes){const d=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function coursePackage(url,env){const parts=url.pathname.split('/'),id=decodeURIComponent(parts[3]),label=decodeURIComponent(parts[5]);const row=await env.DB.prepare(`SELECT r2_object_key,content_sha256 FROM course_versions WHERE course_id=? AND version_label=? AND status='published'`).bind(id,label).first();if(!row)return json({error:'Course version not found'},404);const obj=await env.ASSETS.get(row.r2_object_key);if(!obj)return json({error:'Course object missing from R2'},500);const course=JSON.parse(await obj.text()),files=[{name:'course.json',bytes:new TextEncoder().encode(JSON.stringify(course))}],assets=[];for(const key of collectAssetKeys(course)){const a=await env.ASSETS.get(key);if(!a)continue;const bytes=new Uint8Array(await a.arrayBuffer());files.push({name:key,bytes});const sha256=await sha256Hex(bytes),isImage=/\.(webp|png|jpe?g)$/i.test(key);assets.push({path:key,size:bytes.length,sha256,type:isImage?'image':'audio',asset_id:isImage?'img_'+sha256.slice(0,24):null,partition:isImage?sha256.slice(0,2):null})}files.push({name:'package-manifest.json',bytes:new TextEncoder().encode(JSON.stringify({course_id:id,version:label,asset_revision:course.asset_revision||0,assets},null,2))});const zip=makeStoredZip(files);return new Response(zip,{headers:{...CORS,'Content-Type':'application/zip','Content-Disposition':`attachment; filename="${id}-${label}.zip"`,'Cache-Control':'public,max-age=31536000,immutable'}})}
